version: '3.8'

services:
  mtspostgres:
    image: postgres:12.0
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5437"
    command: -p 5437
    restart: always
  mtsapp:
    build: './'
    image: mtsapp:latest
    restart: always
    environment:
      DATABASE_URL: 'jdbc:postgresql://mtspostgres:5437/postgres'
    ports:
      - 80:8992
    depends_on:
      - mtspostgres